name: Update Naukri Profile

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC (approx. 5:30 AM IST)
  workflow_dispatch: # Allows manual trigger

jobs:
  update-profile:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update Naukri profile
        uses: Prateek-Wayne/naukri-resume-action@main
        with:
          username: ${{ secrets.NAUKRI_USERNAME }}
          password: ${{ secrets.NAUKRI_PASSWORD }}
          profile_id: ${{ secrets.NAUKRI_PROFILE_ID }}
          resume_path: |-
            ./resumes/resume1.pdf
          profile_summary: ${{ vars.NAUKRI_PROFILE_SUMMARY }}
          resume_headline: ${{ vars.NAUKRI_RESUME_HEADLINE }}
