name: Update Naukri Profile

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC (approx. 5:30 AM IST)
  workflow_dispatch: # Allows manual trigger

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate matrix output
        id: set-matrix
        run: node script/parse-profiles.js

  update-profile:
    needs: setup
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update Naukri profile for ${{ matrix.name }}
        uses: ./
        with:
          username: ${{ matrix.username }}
          password: ${{ matrix.password }}
          profile_id: ${{ matrix.profile_id }}
          resume_path: ${{ matrix.resume_path }}
          profile_summary: ${{ matrix.profile_summary }}
          resume_headline: ${{ matrix.resume_headline }}
